# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |global_config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  global_config.vm.box = "precise64"
  global_config.vm.box_url = "http://thammuz.tchpc.tcd.ie/mirrors/boxes/precise64.box"

  global_config.vm.define(:ceph) do |config|
    config.vm.network :hostonly, "192.168.206.110"
    config.vm.host_name = "ceph.localhost"

#    config.vm.provision :ansible do |ansible|
#      # point Vagrant at the location of your playbook you want to run
#      ansible.playbook =  [ "playbooks/setup.yml" ]
#
#      # the Vagrant VM will be put in this host group change this should
#      # match the host group in your playbook you want to test
#      ansible.hosts = [ "ceph" ]
#    end

    config.vm.customize [
      "modifyvm", :id,
      "--name", "ceph VM",
      "--memory", "1024",
    ]
    config.vm.customize [ "createhd", "--filename", "disk-1", "--size", "5000" ]
    config.vm.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 3+1, "--device", 0, "--type", "hdd", "--medium", "disk-1.vdi" ]
  end

end
