# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "sl64-x86_64"
  #config.vm.box_url = "http://objects.tchpc.tcd.ie/baseboxes/scientificlinux-6.2-x86_64-netboot.box"
  config.vm.box = "precise64"
  config.vm.box_url = "http://objects.tchpc.tcd.ie/baseboxes/precise.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
  end

  (0..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.test"
      node.vm.network :private_network, ip: "192.168.206.11#{i}"
      node.vm.network :private_network, ip: "192.168.252.11#{i}"
      (0..1).each do |d|
        node.vm.provider :virtualbox do |vb|
          vb.customize [ "createhd", "--filename", "disk-#{i}-#{d}", "--size", "5000" ]
          vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 3+d, "--device", 0, "--type", "hdd", "--medium", "disk-#{i}-#{d}.vdi" ]
        end
      end
    end
  end

end
